--INSTEAD OF TRIGGER

--An INSTEAD OF trigger is a trigger that allows you to skip an INSERT, DELETE, or UPDATE statement to a table or a view 
--and execute other statements defined in the trigger instead. 
--The actual insert, delete, or update operation does not occur at all.


SELECT * FROM EMP
SELECT * FROM DEPT

CREATE VIEW INSTEAD_VIEW
AS
    SELECT EMPNO, ENAME, DNAME, LOC 
	FROM EMP E 
	LEFT JOIN DEPT D
	ON E.DEPTNO = D.DEPTNO
	

SELECT * FROM INSTEAD_VIEW


INSERT INTO INSTEAD_VIEW VALUES (22,'XYZ_EMPLOYEE','ARTS','MUMBAI')   --ERROR
--View or function 'INSTEAD_VIEW' is not updatable because the modification affects multiple base tables.



CREATE TRIGGER INSTEAD_TRIGGER_INSERT
ON INSTEAD_VIEW
INSTEAD OF INSERT
AS
BEGIN
     DECLARE @DNO INT
	 SELECT @DNO = D.DEPTNO
	 FROM DEPT D
	 INNER JOIN INSERTED I
	 ON I.DNAME = D.DNAME
	  
     IF (@DNO IS NULL)
     BEGIN
	       RAISERROR ('INVALID DEPARTMENT NAME',16,1)
	 END
	 ELSE
	 BEGIN
	      INSERT INTO EMP (EMPNO, ENAME , DEPTNO) SELECT EMPNO, ENAME, @DNO FROM INSERTED
     END
END

DROP TRIGGER INSTEAD_TRIGGER_INSERT





INSERT INTO INSTEAD_VIEW VALUES (22,'XYZ_EMPLOYEE','ARTS','MUMBAI')   --NO ERRORS NOW
INSERT INTO INSTEAD_VIEW VALUES (23,'HELLO', 'SOME_DEPT', 'MUMBAI')   --INVALID DEPT NAME ERROR
 
SELECT * FROM INSTEAD_VIEW





DELETE FROM INSTEAD_VIEW WHERE EMPNO=22   -- ERROR


CREATE TRIGGER INSTEAD_TRIGGER_DELETE
ON INSTEAD_VIEW
INSTEAD OF DELETE
AS
BEGIN
     DECLARE @ENO INT
	 SELECT @ENO = E.EMPNO
	 FROM EMP E
	 INNER JOIN DELETED D
	 ON D.EMPNO = E.EMPNO
	  
     IF (@ENO IS NULL)
     BEGIN
	       RAISERROR ('NO SUCH EMPLOYEE EXISTS',16,1)
	 END
	 ELSE
	 BEGIN
	      DELETE FROM EMP WHERE EMPNO = @ENO
     END
END


DELETE FROM INSTEAD_VIEW WHERE EMPNO=22   -- NO ERROR NOW
DELETE FROM INSTEAD_VIEW WHERE EMPNO=23   -- NO SUCH EMPLOYEE EXISTS ERROR


SELECT * FROM INSTEAD_VIEW



UPDATE INSTEAD_VIEW SET LOC = 'DELHI' WHERE EMPNO = 22










